// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRV2idFE2FRRpv9JN6k-xhrW_6I6fZgg0',
    appId: '1:748087381030:web:f3a4f29b7baee88cbfeae7',
    messagingSenderId: '748087381030',
    projectId: 'gold-gt-project',
    authDomain: 'gold-gt-project.firebaseapp.com',
    storageBucket: 'gold-gt-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjfWIOB0YlBhv2TunTTEIFqYp5sr2witI',
    appId: '1:748087381030:android:d0cdf9f5a1e2a499bfeae7',
    messagingSenderId: '748087381030',
    projectId: 'gold-gt-project',
    storageBucket: 'gold-gt-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZH2HJ2hINT5PhuWTTf31_B43SK2wYks',
    appId: '1:748087381030:ios:66ab5af310992f4cbfeae7',
    messagingSenderId: '748087381030',
    projectId: 'gold-gt-project',
    storageBucket: 'gold-gt-project.appspot.com',
    iosBundleId: 'com.example.gtBankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZH2HJ2hINT5PhuWTTf31_B43SK2wYks',
    appId: '1:748087381030:ios:66ab5af310992f4cbfeae7',
    messagingSenderId: '748087381030',
    projectId: 'gold-gt-project',
    storageBucket: 'gold-gt-project.appspot.com',
    iosBundleId: 'com.example.gtBankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRV2idFE2FRRpv9JN6k-xhrW_6I6fZgg0',
    appId: '1:748087381030:web:f5f7dfafc5acd0b6bfeae7',
    messagingSenderId: '748087381030',
    projectId: 'gold-gt-project',
    authDomain: 'gold-gt-project.firebaseapp.com',
    storageBucket: 'gold-gt-project.appspot.com',
  );

}